# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(blank=True, max_length=20, null=True, verbose_name='agência')),
                ('account', models.CharField(blank=True, max_length=20, null=True, verbose_name='conta')),
                ('digit', models.CharField(blank=True, max_length=20, null=True, verbose_name='dígito')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'contas',
                'verbose_name': 'conta',
            },
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='código')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
            ],
            options={
                'verbose_name_plural': 'bancos',
                'verbose_name': 'banco',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='descrição')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.Category')),
            ],
            options={
                'verbose_name_plural': 'categorias',
                'verbose_name': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nome')),
                ('client', models.BooleanField(default=False, verbose_name='cliente?')),
                ('provider', models.BooleanField(default=False, verbose_name='fornecedor?')),
            ],
            options={
                'verbose_name_plural': 'pessoas',
                'verbose_name': 'pessoa',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Bank', verbose_name='banco'),
        ),
    ]
