# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-15 14:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20161228_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Account',
            new_name='BankAccount',
        ),
    ]
